require 'factory_girl'

require_relative "../spec/factories/client_contacts.rb"
require_relative "../spec/factories/event_title_review.rb"
require_relative "../spec/factories/messages_threads.rb"
require_relative "../spec/factories/messages.rb"
require_relative "../spec/factories/message_classifications.rb"
require_relative "../spec/factories/automated_message_classifications.rb"
require_relative "../spec/factories/automated_julie_actions.rb"
require_relative "../spec/factories/message_interpretations.rb"
require_relative "../spec/factories/julie_actions.rb"
require_relative "../spec/factories/operators.rb"
require_relative "../spec/factories/operator_presence.rb"
require_relative "../spec/factories/operator_actions.rb"
require_relative "../spec/factories/operator_actions_groups.rb"
require_relative "../spec/factories/julie_aliases.rb"
